apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: tc-pipeline-run-
spec:
  serviceAccountName: pipeline
  pipelineRef:
    name: tc-pipeline
  params:
    - name: repo-url
      value: "https://github.com/ilyas-assylbekov/ilyas-assylbekov.github.io"
    - name: branch
      value: "master"
    - name: app-name
      value: "ilyas-assylbekov"
  workspaces:
  - name: pipeline-workspace
    persistentVolumeClaim:
      claimName: pipelinerun-pvc
  - name: dockerconfig-ws
    secret:
      secretName: docker-reg-creds